dist: xenial

services:
  - docker

addons:
  apt:
    source:
      - git-core
    packages:
      - git

language: node_js

before_install:
  - docker pull antora/antora:2.0.0

before_script:
  - npm install

script:
  - docker run -v $TRAVIS_BUILD_DIR:/antora --rm -t antora/antora:2.0.0 --fetch --stacktrace site.yml

after_success:
  - ./travis/push.sh
