dist: xenial

services:
  - docker

addons:
  apt:
    source:
      - git-core
    packages:
      - git

before_install:
  - docker pull antora/antora:2.0.0

script:
  - docker run -v $TRAVIS_BUILD_DIR:/antora --rm -t antora/antora:2.0.0 --fetch --stacktrace site.yml
    cd docs;
    touch .nojekyll;
    git add .;

deploy:
  provider: pages
  skip-cleanup: true
  github-token: ${GH_TOKEN}
  keep-history: true
  on:
    branch: master
