dist: xenial

services:
  - docker

addons:
  apt:
    source:
      - git-core
    packages:
      - git

language: node_js

before_install:
  - docker pull antora/antora:2.0.0

before_script:
  - npm install

script:
  - docker run -v $TRAVIS_BUILD_DIR:/antora --rm -t antora/antora:2.0.0 --clean --fetch --stacktrace site.yml
  - sudo touch docs/.nojekyll
  - git branch
  - git add -A .
  - git commit -a -m 'Travis build'
  - git remote add origin-pages https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git > /dev/null 2>&1
  - git push --all --set-upstream origin-pages master

after_success:
  - ./.travis/push.sh
