site:
  title: OpenDevStack
  start_page: common::index.adoc
content:
  sources:
    - url: https://github.com/rattermeyer/ods-docs-guides.git
    - url: https://github.com/rattermeyer/ods-core.git
      start_path: docs
    - url: https://github.com/rattermeyer/ods-jenkins-shared-library.git
      start_path: docs
    - url: https://github.com/rattermeyer/ods-provisioning-app.git
      start_path: docs
      #    - url: https://git.opitz-consulting.de/scm/opendevstack/ods-common-keycloak.git
      #      start_path: docs
      #    - url: https://git.opitz-consulting.de/scm/opendevstack/ods-jira-keycloak.git
      #      start_path: docs
      #    - url: https://git.opitz-consulting.de/scm/opendevstack/ods-confluence-keycloak.git
      #      start_path: docs
      #    - url: https://git.opitz-consulting.de/scm/opendevstack/ods-bitbucket-keycloak.git
      #      start_path: docs

asciidoc:
  extensions:
    - asciidoctor-plantuml
  attributes:
    plantuml-server-url: 'http://www.plantuml.com/plantuml'
    plantuml-fetch-diagram: true

output:
  dir: ./docs
ui:
  bundle:
    url: ./ui-bundle.zip
    snapshot: true
