site:
  title: OpenDevStack
  start_page: common::index.adoc
  url: https://www.rattermeyer.de/ods-documentation

content:
  sources:
    - url: https://github.com/rattermeyer/opendevstack.github.io
      start_path: docs
    - url: https://github.com/rattermeyer/ods-core.git
      start_path: docs
    - url: https://github.com/rattermeyer/ods-jenkins-shared-library.git
      start_path: docs
    - url: https://github.com/rattermeyer/ods-provisioning-app.git
      start_path: docs

asciidoc:
  extensions:
    - asciidoctor-plantuml
  attributes:
    plantuml-server-url: 'http://www.plantuml.com/plantuml'
    plantuml-fetch-diagram: true

output:
  dir: ./docs
ui:
  bundle:
    url: ./ui-bundle.zip
    snapshot: true
