site:
  title: OpenDevStack
  start_page: common::index.adoc
content:
  sources:
    - url: https://github.com/rattermeyer/ods-guides.git
    - url: https://github.com/rattermeyer/ods-core.git
      start_path: docs
    - url: https://github.com/rattermeyer/ods-jenkins-shared-library.git
      start_path: docs
    - url: https://github.com/rattermeyer/ods-provisioning-app.git
      start_path: docs
output:
  dir: ./docs
ui:
  bundle:
    url: ./ui-bundle.zip
    snapshot: true
